# Usage tips:
# - working on something, and need that to be built first? Temporarily, insert
#   a stage before the others.
# - to make gitlab skip jobs, prepend its name with . (a dot).
# - gitlab: don't forget to set the builds option to clone instead of git fetch
#   see Project Settings -> Builds. Fixes issues new builds not being 100%
#   clean builds.
# - In Project Settings you can also increase the max build time, default 60
#   minutes, to, for example, 180 minutes. 

stages:
  - build
  - deploy

build-rocko-full:
  script:
    - make CONFIG=rocko reconf fetch-all build/conf/bblayers.conf
    - rm -rf /media/data/venus/sstate-cache-tmp
    - export BBPATH_EXTRA="$PWD/sites/ci-master:" && make venus
    - mv /media/data/venus/sstate-cache /media/data/venus/sstate-cache-old && mv /media/data/venus/sstate-cache-tmp /media/data/venus/sstate-cache && rm -rf /media/data/venus/sstate-cache-old
    - ./ci-populate-artifacts.sh rocko
  stage: build
  tags:
    - venus
    - linux
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-rocko.tgz
  only:
    - master
  except:
    - tags

build-rocko:
  script:
    - make CONFIG=rocko reconf fetch-all build/conf/bblayers.conf
    - export BBPATH_EXTRA="$PWD/sites/ci-mirror:" && make swus
    - ./ci-populate-artifacts.sh rocko
    - ./ci-upload-artifacts-to-build-feeds.sh $CI_BUILD_REF_NAME
  stage: build
  tags:
    - venus
    - linux
  except:
    - tags
    - master

deploy:
  only:
    - master
  script:
    - rm -rf artifacts; find . -maxdepth 1 -name "artifacts-*.tgz" -exec tar -xf {} \;
    - ./ci-upload-artifacts-to-build-feeds.sh $CI_BUILD_REF_NAME
    - ./ci-upload-artifacts-to-www.sh
    - "curl -X POST -F token=56bd8d45f917e9ff0ff396005a8c98 -F ref=master https://git.victronenergy.com/api/v4/projects/221/trigger/pipeline"
  stage: deploy
  tags:
    - venus
    - linux
  except:
    - tags
